// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWe3Wwka3YUjlVJgl8qCawB6LmozIG2Ks',
    appId: '1:558868134734:web:7334d52b3761eff44bbc1f',
    messagingSenderId: '558868134734',
    projectId: 'chatmate-u',
    authDomain: 'chatmate-u.firebaseapp.com',
    storageBucket: 'chatmate-u.appspot.com',
    measurementId: 'G-SRX567B1L8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtZTtMdJ2D8b2LALOAy7pWOsKObdKHWww',
    appId: '1:558868134734:android:a7fcaaa3854200714bbc1f',
    messagingSenderId: '558868134734',
    projectId: 'chatmate-u',
    storageBucket: 'chatmate-u.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRAn_NTFHBfMxW2VGKpV_w-zsveUJvDxE',
    appId: '1:558868134734:ios:f7de29f207aa63314bbc1f',
    messagingSenderId: '558868134734',
    projectId: 'chatmate-u',
    storageBucket: 'chatmate-u.appspot.com',
    iosClientId: '558868134734-gjgdif83nkajbmkvob8o4q92mb1tdthi.apps.googleusercontent.com',
    iosBundleId: 'code.jeuel.chatmate',
  );
}
